"use client";

import { motion } from "framer-motion";
import LinkedInPostPreview from "./LinkedInPostPreview";

const EXAMPLE_POST = `\u{1F680} Monolithic AGI vs. Patchwork (Distributed) AGI - Are We Preparing for the Right Future?

For years, AI safety assumed one outcome:
\u{1F449} AGI as a single, monolithic system - one model to align, control, and govern.

But a growing body of research (including Google's Distributional AGI Safety paper) suggests a very different path:
AGI may emerge as a network of specialized agents - not one brain, but many coordinating parts.

\u{1F9E0} Why this shift matters
1\uFE0F\u20E3 Safety is no longer model-level - it's system-level
Aligning one model is hard. Aligning many interacting agents is a fundamentally different challenge.

2\uFE0F\u20E3 Emergent behavior becomes the real risk
When agents coordinate, unintended norms and behaviors can emerge. Safety frameworks built for single systems don't address this.

3\uFE0F\u20E3 Real-world signals are already here
Distributed AI ecosystems expand the attack surface when identity, trust, and permissions aren't governed at the network level.

\u26A0\uFE0F The core takeaway
If AGI emerges through patchwork intelligence, governance and alignment must evolve beyond single-model thinking.

Are our current AI safety strategies preparing us for one AGI, or for an ecosystem of agents?

\u{1F447} Let's discuss in the comments.

#AGI #AISafety #DistributedAI #MultiAgentSystems #AIGovernance`;

export default function ExamplePosts() {
  return (
    <section className="max-w-4xl mx-auto px-6 py-16">
      <motion.h2
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        className="text-2xl font-bold text-gray-900 text-center mb-3"
      >
        Example Output
      </motion.h2>
      <motion.p
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        className="text-sm text-gray-500 text-center mb-8"
      >
        A real post generated by the pipeline
      </motion.p>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
      >
        <LinkedInPostPreview content={EXAMPLE_POST} />
      </motion.div>
    </section>
  );
}
